stages:
  - build

before_script:
  - git submodule update --init --recursive

make_and_test:
  image: analysisrunner
  stage: build
  tags: 
    - Lb2Lemu

  script:
    - xrdfs root://eoslhcb.cern.ch ls /eos/lhcb/user/p/pluca
    - source setup.sh snake
    - snakemake test
    


