stages:
  - build

before_script:
  - git submodule update --init --recursive

make_and_test:
  image: analysisrunner
  stage: build
  tags: 
    - Lb2Lemu

  script:
    - source /root/run_kinit.sh
    - source scripts/setup.sh snake
    - snakemake test --config cvmfs='False'
    


