stages:
  - build

before_script:
  - git submodule update --init --recursive

make_and_test:
  image: analysisrunner
  stage: build
  tags: 
    - Lb2Lemu

  script:
#    - export B2KTAUMUROOT=$PWD
    - source setup.sh snake
#    - export PYTHONPATH=$B2KTAUMUROOT/python:$B2KTAUMUROOT/pyutils:$PYTHONPATH
    - snakemake test
    


