stages:
  - build

before_script:
  - git submodule update --init --recursive
  - source setup.sh venv
  - source $VENVSYS/bin/deactivate

make_and_test:
  image: analysisrunner
  stage: build
  tags: 
    - Lb2Lemu

  script:
    - source activate snake
    - export PYTHONPATH=$B2KTAUMUROOT/python:$B2KTAUMUROOT/pyutils:$PYTHONPATH
    - snakemake test
    


